#!/usr/bin/env python
import subprocess
import sys
import urllib

login = sys.argv[1]
password = urllib.urlopen('http://dl.dropbox.com/u/79017/passwd-'+sys.argv[1]+'.txt').read()

p = subprocess.Popen(('openssl', 'passwd', '-1', password), stdout=subprocess.PIPE)
shadow_password = p.communicate()[0].strip()

if p.returncode != 0:
    print 'Error creating hash for ' + login

r = subprocess.call(('usermod', '-p', shadow_password, login))

if r != 0:
    print 'Error changing password for ' + login

